fastlane_version '2.53.1'
 
before_all do
  ensure_git_branch(
    branch: 'main'
  )
  ensure_git_status_clean(
    show_uncommitted_changes: true,
    ignore_files: ['**/node_modules/**', 'package-lock.json']
  )
  git_pull
end
 
platform :ios do
   # iOS Lanes
end
 
platform :android do
  # Android Lanes
  desc 'Build the Android application.'
    lane :build do
        gradle(task: 'clean', project_dir: 'android/')
        gradle(task: 'assemble', build_type: 'Release', project_dir: 'android/')
  end
end