name: CI/CD Production

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Configura las herramientas necesarias
      - name: Checkout code
        uses: actions/checkout@v4

      # - name: Set up Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: 20 # O la versión que tu proyecto necesita

      # - name: Install Depdencies
      #   run: npm install

      # - name: Run Tests
      #   run: npm run test-no-watch

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Install Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.2
          bundler-cache: true

      #Add Fastlane plugins
      - name: Add Fastlane Plugins
        run: gem install fastlane

      - name: Build Android
        run: fastlane android build

      # - name: Install APK
      #   run: adb install ./android/app/build/outputs/apk/release/app-release.apk

      # - name: Enable KVM group perms
      #   run: |
      #     echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
      #     sudo udevadm control --reload-rules
      #     sudo udevadm trigger --name-match=kvm

      # - uses: dniHze/maestro-test-action@v1
      # - uses: reactivecircus/android-emulator-runner@v2
      #   with:
      #     api-level: 29
      #     arch: x86_64
      #     ram-size: 2048M
      #     target: default
      #     script: |
      #       # Asegúrate de que la aplicación esté instalada en el emulador.
      #       # Si es necesario, puedes instalarla con:
      #       # adb install path/to/your/app.apk

      #       # Inicia la aplicación
      #       #adb shell am start -n com.tuempresa.tuapp/.MainActivity

      #       # Ejecuta los tests de maestro
      #       maestro test --format=junit --output=report.xml --no-ansi .maestro
